import '@styles/globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'
import Sidebar from '@components/Sidebar'
import 'bootstrap/dist/css/bootstrap.css';
const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'SLE Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"data-sidebar-position="fixed" data-header-position="fixed">
          <Sidebar />
          <body className={jakarta.className}>{children}</body>
        </div>
      </body>
    </html>
  )
}
